// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FrameZone_WebApi.Models;

public partial class AAContext : DbContext
{
    public AAContext(DbContextOptions<AAContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CommentImage> CommentImages { get; set; }

    public virtual DbSet<CommentVideo> CommentVideos { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<EventMember> EventMembers { get; set; }

    public virtual DbSet<Follow> Follows { get; set; }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<GroupMember> GroupMembers { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PostImage> PostImages { get; set; }

    public virtual DbSet<PostLike> PostLikes { get; set; }

    public virtual DbSet<PostShare> PostShares { get; set; }

    public virtual DbSet<PostVideo> PostVideos { get; set; }

    public virtual DbSet<PostView> PostViews { get; set; }

    public virtual DbSet<ReportTarget> ReportTargets { get; set; }

    public virtual DbSet<Sticker> Stickers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserBankAccount> UserBankAccounts { get; set; }

    public virtual DbSet<UserLog> UserLogs { get; set; }

    public virtual DbSet<UserNotificationPreference> UserNotificationPreferences { get; set; }

    public virtual DbSet<UserPermission> UserPermissions { get; set; }

    public virtual DbSet<UserPermissionCategory> UserPermissionCategories { get; set; }

    public virtual DbSet<UserPrivacySetting> UserPrivacySettings { get; set; }

    public virtual DbSet<UserPrivateInfo> UserPrivateInfos { get; set; }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserRolePermission> UserRolePermissions { get; set; }

    public virtual DbSet<UserRoleType> UserRoleTypes { get; set; }

    public virtual DbSet<UserSecurity> UserSecurities { get; set; }

    public virtual DbSet<UserSecurityStatus> UserSecurityStatuses { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    public virtual DbSet<UserSystemModule> UserSystemModules { get; set; }

    public virtual DbSet<UserVerification> UserVerifications { get; set; }

    public virtual DbSet<UserVerificationType> UserVerificationTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CommentImage>(entity =>
        {
            entity.ToTable("CommentImages", "SocialNetwork");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__CommentIm__Creat__29A20B3F")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<CommentVideo>(entity =>
        {
            entity.ToTable("CommentVideos", "SocialNetwork");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK_Event");

            entity.ToTable("Events", "SocialNetwork");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeleteAt).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.Location).HasMaxLength(500);
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<EventMember>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("EventMembers", "SocialNetwork");

            entity.Property(e => e.EventId).ValueGeneratedOnAdd();
            entity.Property(e => e.JoinAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.LeftAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Event).WithMany()
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EventMembers_Events");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EventMembers_User");
        });

        modelBuilder.Entity<Follow>(entity =>
        {
            entity.HasKey(e => new { e.FollowerId, e.FollowingId }).HasName("PK_Follow");

            entity.ToTable("Follows", "SocialNetwork");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeleteAt).HasColumnType("datetime");

            entity.HasOne(d => d.Follower).WithMany(p => p.FollowFollowers)
                .HasForeignKey(d => d.FollowerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Follows_User");

            entity.HasOne(d => d.Following).WithMany(p => p.FollowFollowings)
                .HasForeignKey(d => d.FollowingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Follows_User1");
        });

        modelBuilder.Entity<Group>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK_Group");

            entity.ToTable("Groups", "SocialNetwork");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeleteAt).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.GroupName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.GroupType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Owner).WithMany(p => p.Groups)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Groups_User");
        });

        modelBuilder.Entity<GroupMember>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("GroupMembers", "SocialNetwork");

            entity.Property(e => e.GroupId).ValueGeneratedOnAdd();
            entity.Property(e => e.GroupLevel)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.JoinedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.LeftAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Group).WithMany()
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupMembers_Groups");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupMembers_User");
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK_Post");

            entity.ToTable("Posts", "SocialNetwork");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Post__CreatedAt__67E9567B")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.PostContent)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.PostType).HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Post__UpdatedAt__68DD7AB4")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.Posts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Posts_User");
        });

        modelBuilder.Entity<PostImage>(entity =>
        {
            entity.HasKey(e => new { e.ImageId, e.PostId }).HasName("PK_PostImage");

            entity.ToTable("PostImages", "SocialNetwork");

            entity.Property(e => e.ImageId).ValueGeneratedOnAdd();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PostImage__Creat__604834B3")
                .HasColumnType("datetime");
            entity.Property(e => e.DeleteAt).HasColumnType("datetime");
            entity.Property(e => e.SortOrder).HasAnnotation("Relational:DefaultConstraintName", "DF__PostImage__SortO__5F54107A");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PostImage__Updat__613C58EC")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Post).WithMany(p => p.PostImages)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostImages_Posts");
        });

        modelBuilder.Entity<PostLike>(entity =>
        {
            entity.HasKey(e => e.LikeId).HasName("PK_PostLike");

            entity.ToTable("PostLikes", "SocialNetwork");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Post).WithMany(p => p.PostLikes)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostLikes_Posts");

            entity.HasOne(d => d.User).WithMany(p => p.PostLikes)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostLikes_User");
        });

        modelBuilder.Entity<PostShare>(entity =>
        {
            entity.HasKey(e => e.ShareId).HasName("PK_PostShare");

            entity.ToTable("PostShares", "SocialNetwork");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Post).WithMany(p => p.PostShares)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostShares_Posts");

            entity.HasOne(d => d.User).WithMany(p => p.PostShares)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostShares_User");
        });

        modelBuilder.Entity<PostVideo>(entity =>
        {
            entity.HasKey(e => new { e.PostVideoId, e.PostId }).HasName("PK_PostVideo");

            entity.ToTable("PostVideos", "SocialNetwork");

            entity.Property(e => e.PostVideoId).ValueGeneratedOnAdd();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PostVideo__Creat__6CAE0B98")
                .HasColumnType("datetime");
            entity.Property(e => e.DeleteAt).HasColumnType("datetime");
            entity.Property(e => e.SortOrder).HasAnnotation("Relational:DefaultConstraintName", "DF__PostVideo__SortO__6BB9E75F");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PostVideo__Updat__6DA22FD1")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Post).WithMany(p => p.PostVideos)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostVideos_Posts");
        });

        modelBuilder.Entity<PostView>(entity =>
        {
            entity.HasKey(e => e.ViewId).HasName("PK_PostView");

            entity.ToTable("PostViews", "SocialNetwork");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Post).WithMany(p => p.PostViews)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostViews_Posts");

            entity.HasOne(d => d.User).WithMany(p => p.PostViews)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostViews_User");
        });

        modelBuilder.Entity<ReportTarget>(entity =>
        {
            entity.HasKey(e => e.ReportTargetId).HasName("PK_SocialNetwork_ReportTarget");

            entity.ToTable("ReportTarget", "SocialNetwork");

            entity.HasOne(d => d.Post).WithMany(p => p.ReportTargets)
                .HasForeignKey(d => d.PostId)
                .HasConstraintName("FK_ReportTarget_Posts");
        });

        modelBuilder.Entity<Sticker>(entity =>
        {
            entity.HasKey(e => e.StickerId).HasName("PK_Sticker");

            entity.ToTable("Stickers", "SocialNetwork");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeleteAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.StickerName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StickerType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.StickerUrl)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("StickerURL");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK_Member");

            entity.ToTable("User");

            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_User_CreatedBy")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_User_IsDeleted");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.RegistrationSource)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Member_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<UserBankAccount>(entity =>
        {
            entity.HasKey(e => e.BankAccountId);

            entity.ToTable("UserBankAccount");

            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserBankAccount_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserBankAccount_IsActive");
            entity.Property(e => e.IsDefault).HasAnnotation("Relational:DefaultConstraintName", "DF_UserBankAccount_IsDefault");
            entity.Property(e => e.IsVerified).HasAnnotation("Relational:DefaultConstraintName", "DF_UserBankAccount_IsVerified");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserBankAccount_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.VerifiedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UserBankAccounts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserBankAccount_User");
        });

        modelBuilder.Entity<UserLog>(entity =>
        {
            entity.HasKey(e => e.LogId);

            entity.ToTable("UserLog");

            entity.Property(e => e.ActionCategory)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ActionDescription)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ActionType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLog_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DeviceType).HasMaxLength(50);
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(45)
                .HasColumnName("IPAddress");
            entity.Property(e => e.PerformedBy)
                .HasMaxLength(50)
                .HasDefaultValue("User")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLog_PerformedBy");
            entity.Property(e => e.Severity)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Info")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLog_Severity");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Success")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLog_Status");
            entity.Property(e => e.SystemName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TargetType).HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.UserLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserLog_User");
        });

        modelBuilder.Entity<UserNotificationPreference>(entity =>
        {
            entity.HasKey(e => e.PreferenceId).HasName("PK_MemberNotificationPreference");

            entity.ToTable("UserNotificationPreference");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.EmailNotification)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_EmailNotification");
            entity.Property(e => e.MarketingEmail).HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_MarketingEmail");
            entity.Property(e => e.OrderUpdate)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_OrderUpdate");
            entity.Property(e => e.PromotionAlert).HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_PromotionAlert");
            entity.Property(e => e.PushNotification)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_PushNotification");
            entity.Property(e => e.Smsnotification)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_SMSNotification")
                .HasColumnName("SMSNotification");
            entity.Property(e => e.SystemAnnouncement)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_SystemAnnouncement");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UserNotificationPreferences)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserNotificationPreference_User");
        });

        modelBuilder.Entity<UserPermission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK_Permission");

            entity.ToTable("UserPermission");

            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Permission_IsActive");
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PermissionDescription).HasMaxLength(200);
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Category).WithMany(p => p.UserPermissions)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Permission_PermissionCategory");

            entity.HasOne(d => d.System).WithMany(p => p.UserPermissions)
                .HasForeignKey(d => d.SystemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Permission_SystemModule");
        });

        modelBuilder.Entity<UserPermissionCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK_PermissionCategory");

            entity.ToTable("UserPermissionCategory");

            entity.Property(e => e.CategoryCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CategoryDescription).HasMaxLength(200);
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PermissionCategory_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PermissionCategory_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<UserPrivacySetting>(entity =>
        {
            entity.HasKey(e => e.PrivacyId);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserPrivacySettings_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.FieldName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserPrivacySettings_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Visibility)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValueSql("((0))")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserPrivacySettings_Visibility");

            entity.HasOne(d => d.User).WithMany(p => p.UserPrivacySettings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserPrivacySettings_User");
        });

        modelBuilder.Entity<UserPrivateInfo>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("UserPrivateInfo");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.Country).HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserPrivateInfo_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.FullAddress).HasMaxLength(200);
            entity.Property(e => e.Gender).HasMaxLength(20);
            entity.Property(e => e.IdNumber).HasMaxLength(50);
            entity.Property(e => e.PostalCode).HasMaxLength(20);
            entity.Property(e => e.RealName).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserPrivateInfo_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithOne(p => p.UserPrivateInfo)
                .HasForeignKey<UserPrivateInfo>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserPrivateInfo_User");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK_MemberProfile");

            entity.ToTable("UserProfile");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.Avatar).HasMaxLength(500);
            entity.Property(e => e.Bio).HasMaxLength(500);
            entity.Property(e => e.CoverImage).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserProfile_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DisplayName).HasMaxLength(30);
            entity.Property(e => e.Location).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MemberProfile_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Website).HasMaxLength(255);

            entity.HasOne(d => d.User).WithOne(p => p.UserProfile)
                .HasForeignKey<UserProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserProfile_User1");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.UserRoleId).HasName("PK_MemberRole");

            entity.ToTable("UserRole");

            entity.Property(e => e.AssignedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRole_AssignedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRole_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiredAt).HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MemberRole_IsActive");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRole_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.RoleType).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRole_UserRoleType");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRole_User");
        });

        modelBuilder.Entity<UserRolePermission>(entity =>
        {
            entity.HasKey(e => e.RolePermissionId).HasName("PK_RolePermission");

            entity.ToTable("UserRolePermission");

            entity.Property(e => e.CanGrant).HasAnnotation("Relational:DefaultConstraintName", "DF_RolePermission_CanGrant");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RolePermission_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RolePermission_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Permission).WithMany(p => p.UserRolePermissions)
                .HasForeignKey(d => d.PermissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolePermission_Permission");

            entity.HasOne(d => d.RoleType).WithMany(p => p.UserRolePermissions)
                .HasForeignKey(d => d.RoleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolePermission_UserRoleType");
        });

        modelBuilder.Entity<UserRoleType>(entity =>
        {
            entity.HasKey(e => e.RoleTypeId).HasName("PK_RoleType");

            entity.ToTable("UserRoleType");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoleType_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoleType_IsActive");
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RoleDescription).HasMaxLength(200);
            entity.Property(e => e.RoleLevel)
                .HasDefaultValue(4)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoleType_RoleLevel");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoleType_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.System).WithMany(p => p.UserRoleTypes)
                .HasForeignKey(d => d.SystemId)
                .HasConstraintName("FK_UserRoleType_UserSystemModule");
        });

        modelBuilder.Entity<UserSecurity>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("UserSecurity");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSecurity_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.OtpEnabled).HasAnnotation("Relational:DefaultConstraintName", "DF_UserSecurity_TwoFactorEnabled");
            entity.Property(e => e.OtpSecret).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSecurity_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithOne(p => p.UserSecurity)
                .HasForeignKey<UserSecurity>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserSecurity_User1");
        });

        modelBuilder.Entity<UserSecurityStatus>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("UserSecurityStatus");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.IsLocked).HasAnnotation("Relational:DefaultConstraintName", "DF_UserSecurityStatus_IsLocked");
            entity.Property(e => e.LastFailedLoginAt).HasColumnType("datetime");
            entity.Property(e => e.LockedAt).HasColumnType("datetime");
            entity.Property(e => e.LockedBy).HasMaxLength(50);
            entity.Property(e => e.LockedReason).HasMaxLength(255);
            entity.Property(e => e.LockedUntil).HasColumnType("datetime");
            entity.Property(e => e.UnlockedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithOne(p => p.UserSecurityStatus)
                .HasForeignKey<UserSecurityStatus>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserSecurityStatus_User");
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.HasKey(e => e.SessionId);

            entity.ToTable("UserSession");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSession_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiresAt).HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSession_IsActive");
            entity.Property(e => e.LastActivityAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSession_LastActivityAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UserSessions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserSession_User");
        });

        modelBuilder.Entity<UserSystemModule>(entity =>
        {
            entity.HasKey(e => e.SystemId).HasName("PK_SystemModule");

            entity.ToTable("UserSystemModule");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SystemModule_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SystemModule_IsActive");
            entity.Property(e => e.SystemCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SystemDescription).HasMaxLength(200);
            entity.Property(e => e.SystemName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SystemModule_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<UserVerification>(entity =>
        {
            entity.HasKey(e => e.VerificationId).HasName("PK_MemberVerification");

            entity.ToTable("UserVerification");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiredAt).HasColumnType("datetime");
            entity.Property(e => e.FailedAttempts).HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_FailedAttempts");
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(45)
                .HasColumnName("IPAddress");
            entity.Property(e => e.IsUsed).HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_IsUsed");
            entity.Property(e => e.IsVerified).HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_IsVerified");
            entity.Property(e => e.Purpose).HasMaxLength(255);
            entity.Property(e => e.RequestedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_RequestedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.SentTo)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.VerificationCode).HasMaxLength(20);
            entity.Property(e => e.VerificationToken).HasMaxLength(255);
            entity.Property(e => e.VerifiedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UserVerifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserVerification_User");

            entity.HasOne(d => d.VerificationType).WithMany(p => p.UserVerifications)
                .HasForeignKey(d => d.VerificationTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserVerification_UserVerificationType");
        });

        modelBuilder.Entity<UserVerificationType>(entity =>
        {
            entity.HasKey(e => e.VerificationTypeId).HasName("PK_VerificationType");

            entity.ToTable("UserVerificationType");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerificationType_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerificationType_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.VerificationTypeName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}