// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FrameZone_WebApi.Models;

public partial class AAContext : DbContext
{
    public AAContext(DbContextOptions<AAContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Photo> Photos { get; set; }

    public virtual DbSet<PhotoAiclassificationLog> PhotoAiclassificationLogs { get; set; }

    public virtual DbSet<PhotoAiclassificationSuggestion> PhotoAiclassificationSuggestions { get; set; }

    public virtual DbSet<PhotoAlbum> PhotoAlbums { get; set; }

    public virtual DbSet<PhotoCategory> PhotoCategories { get; set; }

    public virtual DbSet<PhotoCategoryType> PhotoCategoryTypes { get; set; }

    public virtual DbSet<PhotoClassificationSource> PhotoClassificationSources { get; set; }

    public virtual DbSet<PhotoFeatureToggle> PhotoFeatureToggles { get; set; }

    public virtual DbSet<PhotoGeneralSetting> PhotoGeneralSettings { get; set; }

    public virtual DbSet<PhotoLocation> PhotoLocations { get; set; }

    public virtual DbSet<PhotoMaintenanceSetting> PhotoMaintenanceSettings { get; set; }

    public virtual DbSet<PhotoMetadatum> PhotoMetadata { get; set; }

    public virtual DbSet<PhotoPhotoAlbum> PhotoPhotoAlbums { get; set; }

    public virtual DbSet<PhotoPhotoCategory> PhotoPhotoCategories { get; set; }

    public virtual DbSet<PhotoPhotoTag> PhotoPhotoTags { get; set; }

    public virtual DbSet<PhotoQuotaType> PhotoQuotaTypes { get; set; }

    public virtual DbSet<PhotoSecuritySetting> PhotoSecuritySettings { get; set; }

    public virtual DbSet<PhotoShare> PhotoShares { get; set; }

    public virtual DbSet<PhotoStorage> PhotoStorages { get; set; }

    public virtual DbSet<PhotoStorageProvider> PhotoStorageProviders { get; set; }

    public virtual DbSet<PhotoSubscriptionHistory> PhotoSubscriptionHistories { get; set; }

    public virtual DbSet<PhotoSubscriptionPlan> PhotoSubscriptionPlans { get; set; }

    public virtual DbSet<PhotoSubscriptionQuotum> PhotoSubscriptionQuota { get; set; }

    public virtual DbSet<PhotoTag> PhotoTags { get; set; }

    public virtual DbSet<PhotoThirdPartyConfig> PhotoThirdPartyConfigs { get; set; }

    public virtual DbSet<PhotoThirdPartyServiceType> PhotoThirdPartyServiceTypes { get; set; }

    public virtual DbSet<PhotoUploadLimitSetting> PhotoUploadLimitSettings { get; set; }

    public virtual DbSet<PhotoUserQuotaUsage> PhotoUserQuotaUsages { get; set; }

    public virtual DbSet<PhotoUserSubscription> PhotoUserSubscriptions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserBankAccount> UserBankAccounts { get; set; }

    public virtual DbSet<UserLog> UserLogs { get; set; }

    public virtual DbSet<UserNotificationPreference> UserNotificationPreferences { get; set; }

    public virtual DbSet<UserPermission> UserPermissions { get; set; }

    public virtual DbSet<UserPermissionCategory> UserPermissionCategories { get; set; }

    public virtual DbSet<UserPrivacySetting> UserPrivacySettings { get; set; }

    public virtual DbSet<UserPrivateInfo> UserPrivateInfos { get; set; }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserRolePermission> UserRolePermissions { get; set; }

    public virtual DbSet<UserRoleType> UserRoleTypes { get; set; }

    public virtual DbSet<UserSecurity> UserSecurities { get; set; }

    public virtual DbSet<UserSecurityStatus> UserSecurityStatuses { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    public virtual DbSet<UserSystemModule> UserSystemModules { get; set; }

    public virtual DbSet<UserVerification> UserVerifications { get; set; }

    public virtual DbSet<UserVerificationType> UserVerificationTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Chinese_Taiwan_Stroke_CI_AS");

        modelBuilder.Entity<Photo>(entity =>
        {
            entity.ToTable("Photo");

            entity.HasIndex(e => new { e.UserId, e.IsDeleted }, "IX_Photo_UserId_IsDeleted");

            entity.HasIndex(e => new { e.UserId, e.IsDeleted, e.UploadedAt }, "IX_Photo_UserId_IsDeleted_UploadedAt").IsDescending(false, false, true);

            entity.HasIndex(e => new { e.UserId, e.UploadedAt }, "IX_Photo_UserId_UploadedAt").IsDescending(false, true);

            entity.HasIndex(e => new { e.UserId, e.Hash }, "UX_Photo_UserId_Hash")
                .IsUnique()
                .HasFilter("([IsDeleted]=(0))");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Photo_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.FileExtension)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Hash)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_Photo_IsDeletedAt");
            entity.Property(e => e.PhotoData).IsRequired();
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Photo_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.UploadedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Photo_UploadedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<PhotoAiclassificationLog>(entity =>
        {
            entity.HasKey(e => e.LogId);

            entity.ToTable("PhotoAIClassificationLog");

            entity.Property(e => e.Aimodel)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("AIModel");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoAIClassificationLog_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ErrorMessage).HasMaxLength(300);
            entity.Property(e => e.ModelVersion).HasMaxLength(30);
            entity.Property(e => e.QuotaUsed)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoAIClassificationLog_QuotaUsed");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Photo).WithMany(p => p.PhotoAiclassificationLogs)
                .HasForeignKey(d => d.PhotoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoAIClassificationLog_Photo");
        });

        modelBuilder.Entity<PhotoAiclassificationSuggestion>(entity =>
        {
            entity.HasKey(e => e.SuggestionId);

            entity.ToTable("PhotoAIClassificationSuggestion");

            entity.Property(e => e.Confidence).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoAIClassificationSuggestion_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsAdopted).HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoAIClassificationSuggestion_IsAdopted");

            entity.HasOne(d => d.Category).WithMany(p => p.PhotoAiclassificationSuggestions)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoAIClassificationSuggestion_PhotoCategory");

            entity.HasOne(d => d.Log).WithMany(p => p.PhotoAiclassificationSuggestions)
                .HasForeignKey(d => d.LogId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoAIClassificationSuggestion_PhotoAIClassificationLog");
        });

        modelBuilder.Entity<PhotoAlbum>(entity =>
        {
            entity.HasKey(e => e.AlbumId).HasName("PK_Album");

            entity.ToTable("PhotoAlbum");

            entity.Property(e => e.AlbumName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Album_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_Album_IsDeleted");
            entity.Property(e => e.IsPublic).HasAnnotation("Relational:DefaultConstraintName", "DF_Album_IsPublic");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Album_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.PhotoAlbums)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoAlbum_User");
        });

        modelBuilder.Entity<PhotoCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId);

            entity.ToTable("PhotoCategory");

            entity.HasIndex(e => e.CategoryId, "IX_PhotoCategory_CategoryId_CategoryName");

            entity.Property(e => e.CategoryCode).HasMaxLength(50);
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoCategory_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoCategory_IsActive");
            entity.Property(e => e.UiType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("flat")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoCategory_UiType_1");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoCategory_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.CategoryType).WithMany(p => p.PhotoCategories)
                .HasForeignKey(d => d.CategoryTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoCategory_PhotoCategoryType");

            entity.HasOne(d => d.User).WithMany(p => p.PhotoCategories)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_PhotoCategory_User");
        });

        modelBuilder.Entity<PhotoCategoryType>(entity =>
        {
            entity.HasKey(e => e.CategoryTypeId).HasName("PK_CategoryType");

            entity.ToTable("PhotoCategoryType");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CategoryType_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CategoryType_IsActive");
            entity.Property(e => e.TypeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CategoryType_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<PhotoClassificationSource>(entity =>
        {
            entity.HasKey(e => e.SourceId);

            entity.ToTable("PhotoClassificationSource");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoClassificationSource_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoClassificationSource_IsActive");
            entity.Property(e => e.SourceCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SourceName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoClassificationSource_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<PhotoFeatureToggle>(entity =>
        {
            entity.HasKey(e => e.FeaturedId);

            entity.ToTable("PhotoFeatureToggle");

            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoFeatureToggle_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.FeatureCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FeatureName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsEnabled)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoFeatureToggle_IsEnabled");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoFeatureToggle_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<PhotoGeneralSetting>(entity =>
        {
            entity.HasKey(e => e.SettingId).HasName("PK_GeneralSetting");

            entity.ToTable("PhotoGeneralSetting");

            entity.Property(e => e.CompanyAddress).HasMaxLength(100);
            entity.Property(e => e.CompanyName).HasMaxLength(100);
            entity.Property(e => e.CompanyPhone).HasMaxLength(50);
            entity.Property(e => e.CompanyTaxId).HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_GeneralSetting_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.FaviconUrl)
                .HasMaxLength(200)
                .HasColumnName("FaviconURL");
            entity.Property(e => e.LogoUrl)
                .HasMaxLength(200)
                .HasColumnName("LogoURL");
            entity.Property(e => e.SupportEmail).HasMaxLength(200);
            entity.Property(e => e.SystemName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SystemVersion)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_GeneralSetting_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.WebSiteDescription).HasMaxLength(200);
            entity.Property(e => e.WebSiteKeywords).HasMaxLength(200);
            entity.Property(e => e.WebSiteTitle)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<PhotoLocation>(entity =>
        {
            entity.HasKey(e => e.LocationId);

            entity.ToTable("PhotoLocation");

            entity.HasIndex(e => new { e.City, e.District }, "IX_PhotoLocation_City_District");

            entity.HasIndex(e => new { e.Country, e.City, e.District }, "IX_PhotoLocation_Country_City");

            entity.HasIndex(e => e.PhotoId, "IX_PhotoLocation_PhotoId");

            entity.HasIndex(e => new { e.PhotoId, e.SourceId }, "UQ_PhotoLocation_PhotoId_SourceId").IsUnique();

            entity.Property(e => e.Address).HasMaxLength(200);
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.Country).HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoLocation_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.District).HasMaxLength(50);
            entity.Property(e => e.Latitude).HasColumnType("decimal(10, 7)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(10, 7)");
            entity.Property(e => e.PlaceName).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoLocation_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Photo).WithMany(p => p.PhotoLocations)
                .HasForeignKey(d => d.PhotoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoLocation_Photo");

            entity.HasOne(d => d.Source).WithMany(p => p.PhotoLocations)
                .HasForeignKey(d => d.SourceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoLocation_PhotoClassificationSource");
        });

        modelBuilder.Entity<PhotoMaintenanceSetting>(entity =>
        {
            entity.HasKey(e => e.SettingId);

            entity.ToTable("PhotoMaintenanceSetting");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoMaintenanceSetting_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.MaintenanceEndTime).HasColumnType("datetime");
            entity.Property(e => e.MaintenanceMessage).HasMaxLength(500);
            entity.Property(e => e.MaintenanceStartTime).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoMaintenanceSetting_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<PhotoMetadatum>(entity =>
        {
            entity.HasKey(e => e.MetadataId);

            entity.HasIndex(e => e.DateTaken, "IX_PhotoMetadata_DateTaken").IsDescending();

            entity.HasIndex(e => e.PhotoId, "IX_PhotoMetadata_PhotoId");

            entity.HasIndex(e => new { e.PhotoId, e.DateTaken }, "IX_PhotoMetadata_PhotoId_DateTaken").IsDescending(false, true);

            entity.Property(e => e.Aperture).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CameraMake).HasMaxLength(200);
            entity.Property(e => e.CameraModel).HasMaxLength(200);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoMetadata_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DateTaken).HasColumnType("datetime");
            entity.Property(e => e.ExposureMode).HasMaxLength(50);
            entity.Property(e => e.FocalLength).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Gpslatitude)
                .HasColumnType("decimal(10, 7)")
                .HasColumnName("GPSLatitude");
            entity.Property(e => e.Gpslongitude)
                .HasColumnType("decimal(10, 7)")
                .HasColumnName("GPSLongitude");
            entity.Property(e => e.Iso).HasColumnName("ISO");
            entity.Property(e => e.LensModel).HasMaxLength(200);
            entity.Property(e => e.ShutterSpeed).HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoMetadata_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.WhiteBalance).HasMaxLength(50);

            entity.HasOne(d => d.Photo).WithMany(p => p.PhotoMetadata)
                .HasForeignKey(d => d.PhotoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoMetadata_Photo");
        });

        modelBuilder.Entity<PhotoPhotoAlbum>(entity =>
        {
            entity.HasKey(e => e.PhotoAlbumId);

            entity.ToTable("PhotoPhotoAlbum");

            entity.Property(e => e.AddedAt).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoPhotoAlbum_CreatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Album).WithMany(p => p.PhotoPhotoAlbums)
                .HasForeignKey(d => d.AlbumId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoPhotoAlbum_PhotoAlbum");

            entity.HasOne(d => d.Photo).WithMany(p => p.PhotoPhotoAlbums)
                .HasForeignKey(d => d.PhotoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoPhotoAlbum_Photo");
        });

        modelBuilder.Entity<PhotoPhotoCategory>(entity =>
        {
            entity.HasKey(e => new { e.PhotoId, e.CategoryId, e.SourceId });

            entity.ToTable("PhotoPhotoCategory");

            entity.HasIndex(e => new { e.CategoryId, e.PhotoId }, "IX_PhotoPhotoCategory_CategoryId_PhotoId");

            entity.HasIndex(e => e.PhotoId, "IX_PhotoPhotoCategory_PhotoId");

            entity.HasIndex(e => new { e.PhotoId, e.SourceId }, "IX_PhotoPhotoCategory_PhotoId_SourceId");

            entity.Property(e => e.AssignedAt).HasColumnType("datetime");
            entity.Property(e => e.Confidence).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoPhotoCategory_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoPhotoCategory_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Category).WithMany(p => p.PhotoPhotoCategories)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoPhotoCategory_PhotoCategory");

            entity.HasOne(d => d.Photo).WithMany(p => p.PhotoPhotoCategories)
                .HasForeignKey(d => d.PhotoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoPhotoCategory_Photo");

            entity.HasOne(d => d.Source).WithMany(p => p.PhotoPhotoCategories)
                .HasForeignKey(d => d.SourceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoPhotoCategory_PhotoClassificationSource");
        });

        modelBuilder.Entity<PhotoPhotoTag>(entity =>
        {
            entity.HasKey(e => new { e.PhotoId, e.TagId, e.SourceId });

            entity.ToTable("PhotoPhotoTag");

            entity.HasIndex(e => e.PhotoId, "IX_PhotoPhotoTag_PhotoId");

            entity.HasIndex(e => new { e.PhotoId, e.SourceId }, "IX_PhotoPhotoTag_PhotoId_SourceId");

            entity.HasIndex(e => new { e.TagId, e.PhotoId }, "IX_PhotoPhotoTag_TagId_PhotoId");

            entity.Property(e => e.AddedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoPhotoTag_AddedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Confidence).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoPhotoTag_CreatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Photo).WithMany(p => p.PhotoPhotoTags)
                .HasForeignKey(d => d.PhotoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoPhotoTag_Photo");

            entity.HasOne(d => d.Source).WithMany(p => p.PhotoPhotoTags)
                .HasForeignKey(d => d.SourceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoPhotoTag_PhotoClassificationSource");

            entity.HasOne(d => d.Tag).WithMany(p => p.PhotoPhotoTags)
                .HasForeignKey(d => d.TagId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoPhotoTag_PhotoTag");
        });

        modelBuilder.Entity<PhotoQuotaType>(entity =>
        {
            entity.HasKey(e => e.QuotaTypeId).HasName("PK_QuotaType");

            entity.ToTable("PhotoQuotaType");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_QuotaType_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_QuotaType_IsActive");
            entity.Property(e => e.QuotaTypeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.QuotaTypeName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.QuotaUnit)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ResetPeriod)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_QuotaType_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.System).WithMany(p => p.PhotoQuotaTypes)
                .HasForeignKey(d => d.SystemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoQuotaType_UserSystemModule");
        });

        modelBuilder.Entity<PhotoSecuritySetting>(entity =>
        {
            entity.HasKey(e => e.SettingId);

            entity.ToTable("PhotoSecuritySetting");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoSecuritySetting_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoSecuritySetting_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<PhotoShare>(entity =>
        {
            entity.HasKey(e => e.ShareId);

            entity.ToTable("PhotoShare");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoShare_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DownloadCount).HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoShare_DownloadCount");
            entity.Property(e => e.ExpiresAt).HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoShare_IsActive");
            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.ShareToken)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ShareType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoShare_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ViewCount).HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoShare_ViewCount");

            entity.HasOne(d => d.Photo).WithMany(p => p.PhotoShares)
                .HasForeignKey(d => d.PhotoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoShare_Photo");

            entity.HasOne(d => d.User).WithMany(p => p.PhotoShares)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoShare_User");
        });

        modelBuilder.Entity<PhotoStorage>(entity =>
        {
            entity.HasKey(e => e.StorageId);

            entity.ToTable("PhotoStorage");

            entity.Property(e => e.AccessUrl)
                .HasMaxLength(1000)
                .HasColumnName("AccessURL");
            entity.Property(e => e.BucketName).HasMaxLength(255);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoStorage_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsPrimary)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoStorage_IsPrimary");
            entity.Property(e => e.Region).HasMaxLength(100);
            entity.Property(e => e.StoragePath)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoStorage_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Photo).WithMany(p => p.PhotoStorages)
                .HasForeignKey(d => d.PhotoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoStorage_Photo");

            entity.HasOne(d => d.Provider).WithMany(p => p.PhotoStorages)
                .HasForeignKey(d => d.ProviderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoStorage_PhotoStorageProvider");
        });

        modelBuilder.Entity<PhotoStorageProvider>(entity =>
        {
            entity.HasKey(e => e.ProviderId);

            entity.ToTable("PhotoStorageProvider");

            entity.Property(e => e.ProviderId).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoStorageProvider_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoStorageProvider_IsActive");
            entity.Property(e => e.ProviderCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProviderName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoStorageProvider_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<PhotoSubscriptionHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryId);

            entity.ToTable("PhotoSubscriptionHistory");

            entity.Property(e => e.ActionType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ChangeReason).HasMaxLength(200);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoSubscriptionHistory_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.EffectiveDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoSubscriptionHistory_EffectiveDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(45)
                .HasColumnName("IPAddress");
            entity.Property(e => e.NewStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.OldStatus).HasMaxLength(20);
            entity.Property(e => e.PerformedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProrationAmount).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Subscription).WithMany(p => p.PhotoSubscriptionHistories)
                .HasForeignKey(d => d.SubscriptionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoSubscriptionHistory_PhotoUserSubscription");

            entity.HasOne(d => d.User).WithMany(p => p.PhotoSubscriptionHistories)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoSubscriptionHistory_User");
        });

        modelBuilder.Entity<PhotoSubscriptionPlan>(entity =>
        {
            entity.HasKey(e => e.PlanId);

            entity.ToTable("PhotoSubscriptionPlan");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoSubscriptionPlan_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoSubscriptionPlan_IsActive");
            entity.Property(e => e.IsPublic)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoSubscriptionPlan_IsPublic");
            entity.Property(e => e.MonthlyPrice)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoSubscriptionPlan_MonthlyPrice")
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.PlanCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PlanDescription).HasMaxLength(200);
            entity.Property(e => e.PlanLevel)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoSubscriptionPlan_PlanLevel");
            entity.Property(e => e.PlanName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoSubscriptionPlan_UpdateAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.System).WithMany(p => p.PhotoSubscriptionPlans)
                .HasForeignKey(d => d.SystemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoSubscriptionPlan_UserSystemModule");
        });

        modelBuilder.Entity<PhotoSubscriptionQuotum>(entity =>
        {
            entity.HasKey(e => e.QuotaId).HasName("PK_SubscriptionQuota");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SubscriptionQuota_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SubscriptionQuota_IsActive");
            entity.Property(e => e.QuotaValue).HasAnnotation("Relational:DefaultConstraintName", "DF_SubscriptionQuota_QuotaValue");
            entity.Property(e => e.ResetDay)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SubscriptionQuota_ResetDay");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SubscriptionQuota_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Plan).WithMany(p => p.PhotoSubscriptionQuota)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoSubscriptionQuota_PhotoSubscriptionPlan");

            entity.HasOne(d => d.QuotaType).WithMany(p => p.PhotoSubscriptionQuota)
                .HasForeignKey(d => d.QuotaTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoSubscriptionQuota_PhotoQuotaType");
        });

        modelBuilder.Entity<PhotoTag>(entity =>
        {
            entity.HasKey(e => e.TagId);

            entity.ToTable("PhotoTag");

            entity.HasIndex(e => e.TagId, "IX_PhotoTag_TagId_TagName");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoTag_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DisplayOrder).HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoTag_DisplayOrder");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoTag_IsActive");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TagType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoTag_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Category).WithMany(p => p.PhotoTags)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoTag_PhotoCategory");

            entity.HasOne(d => d.ParentTag).WithMany(p => p.InverseParentTag)
                .HasForeignKey(d => d.ParentTagId)
                .HasConstraintName("FK_PhotoTag_PhotoTag");
        });

        modelBuilder.Entity<PhotoThirdPartyConfig>(entity =>
        {
            entity.HasKey(e => e.ConfigId);

            entity.ToTable("PhotoThirdPartyConfig");

            entity.Property(e => e.Apikey)
                .HasMaxLength(300)
                .HasColumnName("APIKey");
            entity.Property(e => e.Apisecret)
                .HasMaxLength(300)
                .HasColumnName("APISecret");
            entity.Property(e => e.ConfigJson).HasColumnName("ConfigJSON");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoThirdPartyConfig_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.EndpointUrl)
                .HasMaxLength(300)
                .HasColumnName("EndpointURL");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoThirdPartyConfig_IsActive");
            entity.Property(e => e.IsPrimary)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoThirdPartyConfig_IsPrimary");
            entity.Property(e => e.ProviderName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoThirdPartyConfig_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ServiceType).WithMany(p => p.PhotoThirdPartyConfigs)
                .HasForeignKey(d => d.ServiceTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoThirdPartyConfig_PhotoThirdPartyServiceType");
        });

        modelBuilder.Entity<PhotoThirdPartyServiceType>(entity =>
        {
            entity.HasKey(e => e.ServiceTypeId);

            entity.ToTable("PhotoThirdPartyServiceType");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoThirdPartyServiceType_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoThirdPartyServiceType_IsActive");
            entity.Property(e => e.ServiceCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ServiceName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoThirdPartyServiceType_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<PhotoUploadLimitSetting>(entity =>
        {
            entity.HasKey(e => e.SettingId);

            entity.ToTable("PhotoUploadLimitSetting");

            entity.Property(e => e.AllowedExtensions)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoUploadLimitSetting_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.FreeUserStorageGb).HasColumnName("FreeUserStorageGB");
            entity.Property(e => e.MaxFileSizeMb).HasColumnName("MaxFileSizeMB");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoUploadLimitSetting_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<PhotoUserQuotaUsage>(entity =>
        {
            entity.HasKey(e => e.UsageId);

            entity.ToTable("PhotoUserQuotaUsage");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoUserQuotaUsage_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.PeriodStartDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoUserQuotaUsage_PeriodStartDate")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoUserQuotaUsage_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.UsedAmount).HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoUserQuotaUsage_UsedAmount");

            entity.HasOne(d => d.QuotaType).WithMany(p => p.PhotoUserQuotaUsages)
                .HasForeignKey(d => d.QuotaTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoUserQuotaUsage_PhotoQuotaType");

            entity.HasOne(d => d.Subscription).WithMany(p => p.PhotoUserQuotaUsages)
                .HasForeignKey(d => d.SubscriptionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoUserQuotaUsage_PhotoUserSubscription");

            entity.HasOne(d => d.User).WithMany(p => p.PhotoUserQuotaUsages)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoUserQuotaUsage_User");
        });

        modelBuilder.Entity<PhotoUserSubscription>(entity =>
        {
            entity.HasKey(e => e.SubscriptionId).HasName("PK_UserSubscription");

            entity.ToTable("PhotoUserSubscription");

            entity.Property(e => e.AutoRenew)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSubscription_AutoRenew");
            entity.Property(e => e.BilingCycle)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Month")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_QuotaValue");
            entity.Property(e => e.CancellationReason).HasMaxLength(200);
            entity.Property(e => e.CancelledAt).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSubscription_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.EndDate)
                .HasDefaultValueSql("((0))")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_ResetPeriod")
                .HasColumnType("datetime");
            entity.Property(e => e.StartDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoUserSubscription_StartDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Active")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PhotoUserSubscription_Status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSubscription_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Plan).WithMany(p => p.PhotoUserSubscriptions)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoUserSubscription_PhotoSubscriptionPlan");

            entity.HasOne(d => d.User).WithMany(p => p.PhotoUserSubscriptions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotoUserSubscription_User");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK_Member");

            entity.ToTable("User");

            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_User_CreatedBy")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_User_IsDeleted");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.RegistrationSource)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Member_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<UserBankAccount>(entity =>
        {
            entity.HasKey(e => e.BankAccountId);

            entity.ToTable("UserBankAccount");

            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserBankAccount_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserBankAccount_IsActive");
            entity.Property(e => e.IsDefault).HasAnnotation("Relational:DefaultConstraintName", "DF_UserBankAccount_IsDefault");
            entity.Property(e => e.IsVerified).HasAnnotation("Relational:DefaultConstraintName", "DF_UserBankAccount_IsVerified");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserBankAccount_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.VerifiedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UserBankAccounts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserBankAccount_User");
        });

        modelBuilder.Entity<UserLog>(entity =>
        {
            entity.HasKey(e => e.LogId);

            entity.ToTable("UserLog");

            entity.Property(e => e.ActionCategory)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ActionDescription)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ActionType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLog_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DeviceType).HasMaxLength(50);
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(45)
                .HasColumnName("IPAddress");
            entity.Property(e => e.PerformedBy)
                .HasMaxLength(50)
                .HasDefaultValue("User")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLog_PerformedBy");
            entity.Property(e => e.Severity)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Info")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLog_Severity");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Success")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserLog_Status");
            entity.Property(e => e.SystemName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TargetType).HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.UserLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserLog_User");
        });

        modelBuilder.Entity<UserNotificationPreference>(entity =>
        {
            entity.HasKey(e => e.PreferenceId).HasName("PK_MemberNotificationPreference");

            entity.ToTable("UserNotificationPreference");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.EmailNotification)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_EmailNotification");
            entity.Property(e => e.MarketingEmail).HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_MarketingEmail");
            entity.Property(e => e.OrderUpdate)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_OrderUpdate");
            entity.Property(e => e.PromotionAlert).HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_PromotionAlert");
            entity.Property(e => e.PushNotification)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_PushNotification");
            entity.Property(e => e.Smsnotification)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_SMSNotification")
                .HasColumnName("SMSNotification");
            entity.Property(e => e.SystemAnnouncement)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_SystemAnnouncement");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserNotificationPreference_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UserNotificationPreferences)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserNotificationPreference_User");
        });

        modelBuilder.Entity<UserPermission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK_Permission");

            entity.ToTable("UserPermission");

            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Permission_IsActive");
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PermissionDescription).HasMaxLength(200);
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Category).WithMany(p => p.UserPermissions)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Permission_PermissionCategory");

            entity.HasOne(d => d.System).WithMany(p => p.UserPermissions)
                .HasForeignKey(d => d.SystemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Permission_SystemModule");
        });

        modelBuilder.Entity<UserPermissionCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK_PermissionCategory");

            entity.ToTable("UserPermissionCategory");

            entity.Property(e => e.CategoryCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CategoryDescription).HasMaxLength(200);
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PermissionCategory_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PermissionCategory_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<UserPrivacySetting>(entity =>
        {
            entity.HasKey(e => e.PrivacyId);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserPrivacySettings_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.FieldName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserPrivacySettings_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Visibility)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValueSql("((0))")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserPrivacySettings_Visibility");

            entity.HasOne(d => d.User).WithMany(p => p.UserPrivacySettings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserPrivacySettings_User");
        });

        modelBuilder.Entity<UserPrivateInfo>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("UserPrivateInfo");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.Country).HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserPrivateInfo_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.FullAddress).HasMaxLength(200);
            entity.Property(e => e.Gender).HasMaxLength(20);
            entity.Property(e => e.IdNumber).HasMaxLength(50);
            entity.Property(e => e.PostalCode).HasMaxLength(20);
            entity.Property(e => e.RealName).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserPrivateInfo_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithOne(p => p.UserPrivateInfo)
                .HasForeignKey<UserPrivateInfo>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserPrivateInfo_User");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK_MemberProfile");

            entity.ToTable("UserProfile");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.Avatar).HasMaxLength(500);
            entity.Property(e => e.Bio).HasMaxLength(500);
            entity.Property(e => e.CoverImage).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserProfile_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DisplayName).HasMaxLength(30);
            entity.Property(e => e.Location).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MemberProfile_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Website).HasMaxLength(255);

            entity.HasOne(d => d.User).WithOne(p => p.UserProfile)
                .HasForeignKey<UserProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserProfile_User1");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.UserRoleId).HasName("PK_MemberRole");

            entity.ToTable("UserRole");

            entity.Property(e => e.AssignedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRole_AssignedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRole_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiredAt).HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MemberRole_IsActive");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRole_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.RoleType).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRole_UserRoleType");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRole_User");
        });

        modelBuilder.Entity<UserRolePermission>(entity =>
        {
            entity.HasKey(e => e.RolePermissionId).HasName("PK_RolePermission");

            entity.ToTable("UserRolePermission");

            entity.Property(e => e.CanGrant).HasAnnotation("Relational:DefaultConstraintName", "DF_RolePermission_CanGrant");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RolePermission_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RolePermission_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Permission).WithMany(p => p.UserRolePermissions)
                .HasForeignKey(d => d.PermissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolePermission_Permission");

            entity.HasOne(d => d.RoleType).WithMany(p => p.UserRolePermissions)
                .HasForeignKey(d => d.RoleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolePermission_UserRoleType");
        });

        modelBuilder.Entity<UserRoleType>(entity =>
        {
            entity.HasKey(e => e.RoleTypeId).HasName("PK_RoleType");

            entity.ToTable("UserRoleType");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoleType_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoleType_IsActive");
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RoleDescription).HasMaxLength(200);
            entity.Property(e => e.RoleLevel)
                .HasDefaultValue(4)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoleType_RoleLevel");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoleType_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.System).WithMany(p => p.UserRoleTypes)
                .HasForeignKey(d => d.SystemId)
                .HasConstraintName("FK_UserRoleType_UserSystemModule");
        });

        modelBuilder.Entity<UserSecurity>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("UserSecurity");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSecurity_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.OtpEnabled).HasAnnotation("Relational:DefaultConstraintName", "DF_UserSecurity_TwoFactorEnabled");
            entity.Property(e => e.OtpSecret).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSecurity_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithOne(p => p.UserSecurity)
                .HasForeignKey<UserSecurity>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserSecurity_User1");
        });

        modelBuilder.Entity<UserSecurityStatus>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("UserSecurityStatus");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.IsLocked).HasAnnotation("Relational:DefaultConstraintName", "DF_UserSecurityStatus_IsLocked");
            entity.Property(e => e.LastFailedLoginAt).HasColumnType("datetime");
            entity.Property(e => e.LockedAt).HasColumnType("datetime");
            entity.Property(e => e.LockedBy).HasMaxLength(50);
            entity.Property(e => e.LockedReason).HasMaxLength(255);
            entity.Property(e => e.LockedUntil).HasColumnType("datetime");
            entity.Property(e => e.UnlockedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithOne(p => p.UserSecurityStatus)
                .HasForeignKey<UserSecurityStatus>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserSecurityStatus_User");
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.HasKey(e => e.SessionId);

            entity.ToTable("UserSession");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSession_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiresAt).HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSession_IsActive");
            entity.Property(e => e.LastActivityAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSession_LastActivityAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UserSessions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserSession_User");
        });

        modelBuilder.Entity<UserSystemModule>(entity =>
        {
            entity.HasKey(e => e.SystemId).HasName("PK_SystemModule");

            entity.ToTable("UserSystemModule");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SystemModule_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SystemModule_IsActive");
            entity.Property(e => e.SystemCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SystemDescription).HasMaxLength(200);
            entity.Property(e => e.SystemName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SystemModule_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<UserVerification>(entity =>
        {
            entity.HasKey(e => e.VerificationId).HasName("PK_MemberVerification");

            entity.ToTable("UserVerification");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiredAt).HasColumnType("datetime");
            entity.Property(e => e.FailedAttempts).HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_FailedAttempts");
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(45)
                .HasColumnName("IPAddress");
            entity.Property(e => e.IsUsed).HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_IsUsed");
            entity.Property(e => e.IsVerified).HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_IsVerified");
            entity.Property(e => e.Purpose).HasMaxLength(255);
            entity.Property(e => e.RequestedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_RequestedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.SentTo)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerification_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.VerificationCode).HasMaxLength(20);
            entity.Property(e => e.VerificationToken).HasMaxLength(255);
            entity.Property(e => e.VerifiedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UserVerifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserVerification_User");

            entity.HasOne(d => d.VerificationType).WithMany(p => p.UserVerifications)
                .HasForeignKey(d => d.VerificationTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserVerification_UserVerificationType");
        });

        modelBuilder.Entity<UserVerificationType>(entity =>
        {
            entity.HasKey(e => e.VerificationTypeId).HasName("PK_VerificationType");

            entity.ToTable("UserVerificationType");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerificationType_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserVerificationType_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.VerificationTypeName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}