// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class BellNotification
{
    public long NotificationId { get; set; }

    public int SystemId { get; set; }

    public int? TemplateId { get; set; }

    public int CategoryId { get; set; }

    public int PriorityId { get; set; }

    public string NotificationTitle { get; set; }

    public string NotificationContent { get; set; }

    public string RelatedObjectType { get; set; }

    public long? RelatedObjectId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public virtual ICollection<BellNotificationArchive> BellNotificationArchives { get; set; } = new List<BellNotificationArchive>();

    public virtual ICollection<BellNotificationRecipient> BellNotificationRecipients { get; set; } = new List<BellNotificationRecipient>();

    public virtual Category Category { get; set; }

    public virtual Priority Priority { get; set; }

    public virtual UserSystemModule System { get; set; }

    public virtual Template Template { get; set; }
}