// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class BellNotificationPreference
{
    public long SettingId { get; set; }

    public long UserId { get; set; }

    public int SystemId { get; set; }

    public int CategoryId { get; set; }

    public bool IsEnabled { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Category Category { get; set; }

    public virtual UserSystemModule System { get; set; }

    public virtual User User { get; set; }
}