// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class BellNotificationArchive
{
    public long ArchiveId { get; set; }

    public long OriginalRecipientId { get; set; }

    public long NotificationId { get; set; }

    public long UserId { get; set; }

    public bool IsRead { get; set; }

    public DateTime? ReadAt { get; set; }

    public string ArchiveReason { get; set; }

    public DateTime OriginalCreatedAt { get; set; }

    public DateTime OriginalUpdatedAt { get; set; }

    public DateTime ArchivedAt { get; set; }

    public virtual BellNotification Notification { get; set; }

    public virtual User User { get; set; }
}