// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class BuyerCoupon
{
    public int BuyerCouponId { get; set; }

    public long UserId { get; set; }

    public int CouponId { get; set; }

    public bool IsUsed { get; set; }

    public long? UsedAtOrderId { get; set; }

    public DateTime ExpirationTime { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Product UsedAtOrder { get; set; }

    public virtual User User { get; set; }
}