// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class BuyerDetail
{
    public int BuyerDetailsId { get; set; }

    public long UserId { get; set; }

    public long? PaymentMethodId { get; set; }

    public int? ConvenienceStoreId { get; set; }

    public int? AddressId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ReceivingAddress Address { get; set; }

    public virtual PickupConvenienceStore ConvenienceStore { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual User User { get; set; }
}