// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public int SystemId { get; set; }

    public string CategoryCode { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<BellNotificationPreference> BellNotificationPreferences { get; set; } = new List<BellNotificationPreference>();

    public virtual ICollection<BellNotification> BellNotifications { get; set; } = new List<BellNotification>();

    public virtual UserSystemModule System { get; set; }

    public virtual ICollection<Template> Templates { get; set; } = new List<Template>();
}