// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Channel
{
    public long ChannelId { get; set; }

    public long UserId { get; set; }

    public string ChannelName { get; set; }

    public string Description { get; set; }

    public string Banner { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual User ChannelNavigation { get; set; }

    public virtual ICollection<Following> Followings { get; set; } = new List<Following>();

    public virtual ICollection<Video> Videos { get; set; } = new List<Video>();
}