// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class CommentTarget
{
    public int CommentTargetId { get; set; }

    public int TargetTypeId { get; set; }

    public int? CommentId { get; set; }

    public int? VideoId { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual TargetType TargetType { get; set; }

    public virtual Video Video { get; set; }
}