// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class CommentVideo
{
    public int CommentVideoId { get; set; }

    public int VideoId { get; set; }

    public int CommentId { get; set; }

    public int SortOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual Video Video { get; set; }
}