// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class CommentTarget
{
    public int CommentTargetId { get; set; }

    public int TargetTypeId { get; set; }

    public int? PostId { get; set; }

    public int? VideoId { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual Post Post { get; set; }

    public virtual TargetType TargetType { get; set; }

    public virtual Video Video { get; set; }
}