// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Favorite
{
    public int FavoriteId { get; set; }

    public long UserId { get; set; }

    public long? ProductId { get; set; }

    public int? PhotographerId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Photographer Photographer { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}