// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Message
{
    public int MessageId { get; set; }

    public int RoomId { get; set; }

    public long SenderUserId { get; set; }

    public string MessageContent { get; set; }

    public string MessageType { get; set; }

    public int? StickerId { get; set; }

    public string MediaUrl { get; set; }

    public string ThumbnailUrl { get; set; }

    public long? ProductId { get; set; }

    public int? OrderId { get; set; }

    public string LinkTitle { get; set; }

    public string LinkDescription { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<MessageRead> MessageReads { get; set; } = new List<MessageRead>();

    public virtual ChatRoom Room { get; set; }

    public virtual User SenderUser { get; set; }
}