// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class MessageRead
{
    public int MessageId { get; set; }

    public long UserId { get; set; }

    public DateTime ReadAt { get; set; }

    public virtual Message Message { get; set; }

    public virtual User User { get; set; }
}