// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class PhotoTag
{
    public int TagId { get; set; }

    public int CategoryId { get; set; }

    public string TagName { get; set; }

    public string TagType { get; set; }

    public int? ParentTagId { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual PhotoCategory Category { get; set; }

    public virtual ICollection<PhotoTag> InverseParentTag { get; set; } = new List<PhotoTag>();

    public virtual PhotoTag ParentTag { get; set; }

    public virtual ICollection<PhotoAiclassificationSuggestion> PhotoAiclassificationSuggestions { get; set; } = new List<PhotoAiclassificationSuggestion>();

    public virtual ICollection<PhotoPhotoTag> PhotoPhotoTags { get; set; } = new List<PhotoPhotoTag>();
}