// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class PhotoAiclassificationLog
{
    public long LogId { get; set; }

    public long PhotoId { get; set; }

    public string Aimodel { get; set; }

    public string ModelVersion { get; set; }

    public string Status { get; set; }

    public int? ProcessingTimeMs { get; set; }

    public string ErrorMessage { get; set; }

    public int QuotaUsed { get; set; }

    public DateTime CreatedAt { get; set; }

    public long UserId { get; set; }

    public DateTime AnalyzedAt { get; set; }

    public string AzureVisionResponse { get; set; }

    public string GooglePlacesResponse { get; set; }

    public string ClaudeResponse { get; set; }

    public int? TokensInput { get; set; }

    public int? TokensOutput { get; set; }

    public virtual Photo Photo { get; set; }

    public virtual ICollection<PhotoAiclassificationSuggestion> PhotoAiclassificationSuggestions { get; set; } = new List<PhotoAiclassificationSuggestion>();

    public virtual User User { get; set; }
}