// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class PhotoMetadatum
{
    public long MetadataId { get; set; }

    public long PhotoId { get; set; }

    public string CameraMake { get; set; }

    public string CameraModel { get; set; }

    public DateTime? DateTaken { get; set; }

    public decimal? Gpslatitude { get; set; }

    public decimal? Gpslongitude { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public decimal? FocalLength { get; set; }

    public decimal? Aperture { get; set; }

    public string ShutterSpeed { get; set; }

    public int? Iso { get; set; }

    public string ExposureMode { get; set; }

    public string WhiteBalance { get; set; }

    public string LensModel { get; set; }

    public int? Orientation { get; set; }

    public int? Width { get; set; }

    public int? Height { get; set; }

    public virtual Photo Photo { get; set; }
}