// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Photographer
{
    public int PhotographerId { get; set; }

    public long UserId { get; set; }

    public string StudioType { get; set; }

    public string StudioName { get; set; }

    public string DisplayName { get; set; }

    public string StudioAddress { get; set; }

    public string Description { get; set; }

    public int? YearsOfExperience { get; set; }

    public string AvatarUrl { get; set; }

    public string PortfolioUrl { get; set; }

    public string IdcardUrl { get; set; }

    public string PortfolioFile { get; set; }

    public string VerificationStatus { get; set; }

    public DateTime? VerificationDate { get; set; }

    public long? VerifiedByUserId { get; set; }

    public string RejectionReason { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AvailableSlot> AvailableSlots { get; set; } = new List<AvailableSlot>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual ICollection<PhotographerService> PhotographerServices { get; set; } = new List<PhotographerService>();

    public virtual ICollection<PhotographerSpecialty> PhotographerSpecialties { get; set; } = new List<PhotographerSpecialty>();

    public virtual ICollection<PhotographerVerificationHistory> PhotographerVerificationHistories { get; set; } = new List<PhotographerVerificationHistory>();

    public virtual ICollection<ServiceArea> ServiceAreas { get; set; } = new List<ServiceArea>();

    public virtual User User { get; set; }
}