// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Playlist
{
    public int PlaylistId { get; set; }

    public long UserId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string PrivacyStatus { get; set; }

    public int VideoCount { get; set; }

    public virtual User User { get; set; }

    public virtual UserSavedPlaylist UserSavedPlaylist { get; set; }
}