// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Priority
{
    public int PriorityId { get; set; }

    public string PriorityCode { get; set; }

    public string PriorityName { get; set; }

    public int PriorityLevel { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<BellNotification> BellNotifications { get; set; } = new List<BellNotification>();
}