// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Product
{
    public long ProductId { get; set; }

    public long UserId { get; set; }

    public string ProductName { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public string AuditStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<BuyerCoupon> BuyerCoupons { get; set; } = new List<BuyerCoupon>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<ProductAudit> ProductAudits { get; set; } = new List<ProductAudit>();

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual ICollection<ProductProperty> ProductProperties { get; set; } = new List<ProductProperty>();

    public virtual ICollection<ProductSellerCategoryMappin> ProductSellerCategoryMappins { get; set; } = new List<ProductSellerCategoryMappin>();

    public virtual ICollection<ProductShippingOption> ProductShippingOptions { get; set; } = new List<ProductShippingOption>();

    public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; } = new List<ProductSpecification>();

    public virtual ICollection<ReportTarget> ReportTargets { get; set; } = new List<ReportTarget>();

    public virtual User User { get; set; }
}