// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class ReportTarget
{
    public int ReportTargetId { get; set; }

    public int TargetTypeId { get; set; }

    public long ProductId { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual TargetType TargetType { get; set; }
}