// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public int CategoryId { get; set; }

    public long ReporterUserId { get; set; }

    public long ReportedUserId { get; set; }

    public int? ReportTargetId { get; set; }

    public string Description { get; set; }

    public byte Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ReportCategory Category { get; set; }

    public virtual ICollection<ReportAction> ReportActions { get; set; } = new List<ReportAction>();

    public virtual ReportTarget ReportTarget { get; set; }

    public virtual ReportTarget2 ReportTarget1 { get; set; }

    public virtual ReportTarget1 ReportTargetNavigation { get; set; }

    public virtual User ReportedUser { get; set; }

    public virtual User ReporterUser { get; set; }
}