// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class ReportAction
{
    public int ActionId { get; set; }

    public int ReportId { get; set; }

    public long AdminUserId { get; set; }

    public byte ActionType { get; set; }

    public string ActionResult { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User AdminUser { get; set; }

    public virtual Report Report { get; set; }
}