// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class ReportTarget
{
    public int ReportTargetId { get; set; }

    public int TargetTypeId { get; set; }

    public int? CommentId { get; set; }

    public int? PostId { get; set; }

    public int? MessageId { get; set; }

    public virtual Post Post { get; set; }
}