// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int? OrderDetailsId { get; set; }

    public int? BookingId { get; set; }

    public long ReviewerUserId { get; set; }

    public long RevieweeUserId { get; set; }

    public string ReviewType { get; set; }

    public byte Rating { get; set; }

    public string ReviewContent { get; set; }

    public string ReviewerReply { get; set; }

    public string RevieweeReply { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ReviewPhoto> ReviewPhotos { get; set; } = new List<ReviewPhoto>();

    public virtual User RevieweeUser { get; set; }

    public virtual User ReviewerUser { get; set; }
}