// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class SpecialtyCategory
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<SpecialtyTag> SpecialtyTags { get; set; } = new List<SpecialtyTag>();
}