// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class SpecialtyTag
{
    public int SpecialtyTagId { get; set; }

    public string SpecialtyName { get; set; }

    public int? CategoryId { get; set; }

    public string Description { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual SpecialtyCategory Category { get; set; }

    public virtual ICollection<PhotographerSpecialty> PhotographerSpecialties { get; set; } = new List<PhotographerSpecialty>();
}