// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class TargetType
{
    public int TargetTypeId { get; set; }

    public int SystemId { get; set; }

    public string TargetType1 { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CommentTarget> CommentTargets { get; set; } = new List<CommentTarget>();

    public virtual ICollection<ReportTarget> ReportTargets { get; set; } = new List<ReportTarget>();

    public virtual UserSystemModule System { get; set; }
}