// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Template
{
    public int TemplateId { get; set; }

    public int SystemId { get; set; }

    public string TemplateCode { get; set; }

    public string TemplateName { get; set; }

    public string TemplateType { get; set; }

    public int CategoryId { get; set; }

    public string Subject { get; set; }

    public string ContentTemplate { get; set; }

    public string Variables { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<BellNotification> BellNotifications { get; set; } = new List<BellNotification>();

    public virtual Category Category { get; set; }

    public virtual UserSystemModule System { get; set; }
}