// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class User
{
    public long UserId { get; set; }

    public string Account { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Password { get; set; }

    public string AccountType { get; set; }

    public string AccountStatus { get; set; }

    public string RegistrationSource { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<BuyerAbnormal> BuyerAbnormals { get; set; } = new List<BuyerAbnormal>();

    public virtual ICollection<BuyerCoupon> BuyerCoupons { get; set; } = new List<BuyerCoupon>();

    public virtual ICollection<BuyerDetail> BuyerDetails { get; set; } = new List<BuyerDetail>();

    public virtual Channel Channel { get; set; }

    public virtual ICollection<ChatMember> ChatMembers { get; set; } = new List<ChatMember>();

    public virtual ICollection<CommentLike> CommentLikes { get; set; } = new List<CommentLike>();

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<Coupon> Coupons { get; set; } = new List<Coupon>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual ICollection<Follow> FollowFollowers { get; set; } = new List<Follow>();

    public virtual ICollection<Follow> FollowFollowings { get; set; } = new List<Follow>();

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    public virtual ICollection<InvoiceSetting> InvoiceSettings { get; set; } = new List<InvoiceSetting>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<MessageRead> MessageReads { get; set; } = new List<MessageRead>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PaymentMethod> PaymentMethods { get; set; } = new List<PaymentMethod>();

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();

    public virtual ICollection<PayoutBatch> PayoutBatches { get; set; } = new List<PayoutBatch>();

    public virtual ICollection<PhotoAlbum> PhotoAlbums { get; set; } = new List<PhotoAlbum>();

    public virtual ICollection<PhotoCategory> PhotoCategories { get; set; } = new List<PhotoCategory>();

    public virtual ICollection<PhotoShare> PhotoShares { get; set; } = new List<PhotoShare>();

    public virtual ICollection<PhotoSubscriptionHistory> PhotoSubscriptionHistories { get; set; } = new List<PhotoSubscriptionHistory>();

    public virtual ICollection<PhotoTag> PhotoTags { get; set; } = new List<PhotoTag>();

    public virtual ICollection<PhotoUserQuotaUsage> PhotoUserQuotaUsages { get; set; } = new List<PhotoUserQuotaUsage>();

    public virtual ICollection<PhotoUserSubscription> PhotoUserSubscriptions { get; set; } = new List<PhotoUserSubscription>();

    public virtual ICollection<Photographer> Photographers { get; set; } = new List<Photographer>();

    public virtual ICollection<PickupConvenienceStore> PickupConvenienceStores { get; set; } = new List<PickupConvenienceStore>();

    public virtual ICollection<Playlist> Playlists { get; set; } = new List<Playlist>();

    public virtual ICollection<PostLike> PostLikes { get; set; } = new List<PostLike>();

    public virtual ICollection<PostShare> PostShares { get; set; } = new List<PostShare>();

    public virtual ICollection<PostView> PostViews { get; set; } = new List<PostView>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<ProductAudit> ProductAudits { get; set; } = new List<ProductAudit>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<ReceivingAddress> ReceivingAddresses { get; set; } = new List<ReceivingAddress>();

    public virtual ICollection<RefundRequest> RefundRequests { get; set; } = new List<RefundRequest>();

    public virtual ICollection<ReportAction> ReportActions { get; set; } = new List<ReportAction>();

    public virtual ICollection<Report> ReportReportedUsers { get; set; } = new List<Report>();

    public virtual ICollection<Report> ReportReporterUsers { get; set; } = new List<Report>();

    public virtual ICollection<Review> ReviewRevieweeUsers { get; set; } = new List<Review>();

    public virtual ICollection<Review> ReviewReviewerUsers { get; set; } = new List<Review>();

    public virtual ICollection<SellerAuditHistory> SellerAuditHistoryAdministratorUsers { get; set; } = new List<SellerAuditHistory>();

    public virtual ICollection<SellerAuditHistory> SellerAuditHistorySellerUsers { get; set; } = new List<SellerAuditHistory>();

    public virtual ICollection<SellerCategory> SellerCategories { get; set; } = new List<SellerCategory>();

    public virtual ICollection<SellerDetail> SellerDetailAdministratorUsers { get; set; } = new List<SellerDetail>();

    public virtual ICollection<SellerDetail> SellerDetailSellerUsers { get; set; } = new List<SellerDetail>();

    public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; } = new List<ShoppingCart>();

    public virtual ICollection<StoreBasicInformation> StoreBasicInformations { get; set; } = new List<StoreBasicInformation>();

    public virtual ICollection<UserBankAccount> UserBankAccounts { get; set; } = new List<UserBankAccount>();

    public virtual ICollection<UserLog> UserLogs { get; set; } = new List<UserLog>();

    public virtual ICollection<UserNotificationPreference> UserNotificationPreferences { get; set; } = new List<UserNotificationPreference>();

    public virtual ICollection<UserPrivacySetting> UserPrivacySettings { get; set; } = new List<UserPrivacySetting>();

    public virtual UserPrivateInfo UserPrivateInfo { get; set; }

    public virtual UserProfile UserProfile { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();

    public virtual ICollection<UserSavedPlaylist> UserSavedPlaylists { get; set; } = new List<UserSavedPlaylist>();

    public virtual UserSecurity UserSecurity { get; set; }

    public virtual UserSecurityStatus UserSecurityStatus { get; set; }

    public virtual ICollection<UserSession> UserSessions { get; set; } = new List<UserSession>();

    public virtual ICollection<UserVerification> UserVerifications { get; set; } = new List<UserVerification>();

    public virtual ICollection<WalletTransaction> WalletTransactions { get; set; } = new List<WalletTransaction>();
}