// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

/// <summary>
/// 使用者第三方登入認證資料表
/// </summary>
public partial class UserThirdPartyAuth
{
    /// <summary>
    /// 第三方登入認證ID
    /// </summary>
    public long AuthId { get; set; }

    /// <summary>
    /// 使用者ID
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// 第三方提供者 (Google, Facebook, GitHub, Line)
    /// </summary>
    public string Provider { get; set; }

    /// <summary>
    /// 第三方平台的使用者唯一識別碼
    /// </summary>
    public string ProviderId { get; set; }

    public string ProviderEmail { get; set; }

    public string ProviderName { get; set; }

    public string ProviderAvatar { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? TokenExpiresAt { get; set; }

    public string Scope { get; set; }

    public string RawData { get; set; }

    public bool IsActive { get; set; }

    public bool IsPrimary { get; set; }

    public DateTime? LastUsedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User User { get; set; }
}