// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrameZone_WebApi.Models;

public partial class Video
{
    public int VideoId { get; set; }

    public long ChannelId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string VideoUrl { get; set; }

    public string ThumbnailUrl { get; set; }

    public int? Duration { get; set; }

    public string Resolution { get; set; }

    public string RenditionsData { get; set; }

    public long? FileSize { get; set; }

    public string ProcessStatus { get; set; }

    public string PrivacyStatus { get; set; }

    public bool IsFeatured { get; set; }

    public string AiAuditResult { get; set; }

    public DateTime? PublishDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual Channel Channel { get; set; }

    public virtual ICollection<CommentTarget> CommentTargets { get; set; } = new List<CommentTarget>();

    public virtual ICollection<ReportTarget> ReportTargets { get; set; } = new List<ReportTarget>();
}